Start-Transcript -Path "$env:USERPROFILE\Desktop\winget_log.txt"
winget upgrade MichaelTippach.ASIO4ALL
winget upgrade AutoHotkey.AutoHotkey
winget upgrade Bambulab.Bambustudio
winget upgrade calibre.calibre
winget upgrade Kitware.CMake
winget upgrade CrystalDewWorld.CrystalDiskInfo
winget upgrade Anysphere.Cursor
winget upgrade Docker.DockerDesktop
winget upgrade AdrienAllard.FileConverter
winget upgrade Levitsky.FontBase
winget upgrade PeterPawlowski.foobar2000
winget upgrade Git.Git
winget upgrade GitHub.GitHubDesktop
winget upgrade charmbracelet.glow
winget upgrade Grammarly.Grammarly
winget upgrade ArobasMusic.GuitarPro.8
winget upgrade TheDocumentFoundation.LibreOffice
winget upgrade Microsoft.VCRedist.2015+.x64
winget upgrade Microsoft.VCRedist.2015+.x86
winget upgrade OpenJS.NodeJS.LTS
winget upgrade lencx.Noi
winget upgrade Notepad++.Notepad++
winget upgrade Obsidian.Obsidian
winget upgrade Ollama.Ollama
winget upgrade Open-Shell.Open-Shell-Menu
winget upgrade JohnMacFarlane.Pandoc
winget upgrade Proton.ProtonVPN
winget upgrade JetBrains.PyCharm.Community
winget upgrade Microsoft.VisualStudio.2019.BuildTools
winget upgrade Microsoft.WindowsPCHealthCheck
winget upgrade RARLab.WinRAR
winget upgrade Python.Python.3.12
Stop-Transcript
